export const quickTickers = [
  "AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "META", "NVDA", "NFLX", "AMD", "INTC",
  "PYPL", "ADBE", "CSCO", "PEP", "AVGO", "COST", "CMCSA", "TMUS", "TXN", "QCOM",
  "HON", "AMAT", "SBUX", "AMGN", "ADI", "ADP", "ISRG", "MDLZ", "GILD", "BKNG",
  "VRTX", "REGN", "ZM", "ATVI", "MELI", "LRCX", "CSX", "CHTR", "MU", "PANW",
  "SNPS", "KLAC", "CDNS", "ASML", "MNST", "ORLY", "KDP", "MAR", "FTNT", "MCHP",
  "AZN", "CTAS", "NXPI", "PCAR", "ADSK", "IDXX", "LULU", "CPRT", "PAYX", "ROST",
  "SGEN", "EA", "EXC", "CTSH", "BKR", "ODFL", "KLA", "TEAM", "WDAY", "DDOG",
  "MDB", "ZS", "OKTA", "TTD", "SE", "SHOP", "NET", "AFRM", "PLTR", "U",
  "RBLX", "DKNG", "COIN", "HOOD", "ABNB", "DASH", "SQ", "ROKU", "TDOC", "TWLO",
  "CRWD", "Z", "PATH", "GME", "AMC", "BB", "NOK", "SPY", "QQQ", "IWM",
  "DIA", "VXX", "PFE", "JPM", "V", "MA", "UNH", "HD", "PG", "DIS",
  "BAC", "VZ", "ADBE", "CRM", "XOM", "CVX", "KO", "ABT", "CSCO", "MCD",
  "T", "WMT", "NKE", "LLY", "ABBV", "MRK", "ORCL", "ACN", "AVGO", "COST",
  "TMO", "DHR", "MDT", "NEE", "LIN", "PM", "TXN", "NXT", "AMAT", "LOW",
  "RTX", "HON", "IBM", "INTU", "GS", "MS", "BLK", "NOW", "AXP", "GE",
  "CAT", "DE", "MMM", "UPS", "FDX", "LMT", "BA", "GD", "NOC", "WM",
  "SPGI", "ZTS", "PLD", "AMT", "CCI", "EQIX", "DLR", "PSA", "O", "WELL",
];
